//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiscoDevice) DeepCopyInto(out *CiscoDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiscoDevice.
func (in *CiscoDevice) DeepCopy() *CiscoDevice {
	if in == nil {
		return nil
	}
	out := new(CiscoDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CiscoDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiscoDeviceList) DeepCopyInto(out *CiscoDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CiscoDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiscoDeviceList.
func (in *CiscoDeviceList) DeepCopy() *CiscoDeviceList {
	if in == nil {
		return nil
	}
	out := new(CiscoDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CiscoDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSpec) DeepCopyInto(out *DeviceSpec) {
	*out = *in
	if in.CredentialSecretRef != nil {
		in, out := &in.CredentialSecretRef, &out.CredentialSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]v1.Taint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ResourceLimits.DeepCopyInto(&out.ResourceLimits)
	if in.XE != nil {
		in, out := &in.XE, &out.XE
		*out = new(XEConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSpec.
func (in *DeviceSpec) DeepCopy() *DeviceSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceStatus) DeepCopyInto(out *DeviceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceStatus.
func (in *DeviceStatus) DeepCopy() *DeviceStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceConfig) DeepCopyInto(out *ResourceConfig) {
	*out = *in
	if in.Others != nil {
		in, out := &in.Others, &out.Others
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceConfig.
func (in *ResourceConfig) DeepCopy() *ResourceConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEAppGigabitEthernetConfig) DeepCopyInto(out *XEAppGigabitEthernetConfig) {
	*out = *in
	out.VlanIf = in.VlanIf
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEAppGigabitEthernetConfig.
func (in *XEAppGigabitEthernetConfig) DeepCopy() *XEAppGigabitEthernetConfig {
	if in == nil {
		return nil
	}
	out := new(XEAppGigabitEthernetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEConfig) DeepCopyInto(out *XEConfig) {
	*out = *in
	in.Networking.DeepCopyInto(&out.Networking)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEConfig.
func (in *XEConfig) DeepCopy() *XEConfig {
	if in == nil {
		return nil
	}
	out := new(XEConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEInterfaceConfig) DeepCopyInto(out *XEInterfaceConfig) {
	*out = *in
	if in.VirtualPortGroup != nil {
		in, out := &in.VirtualPortGroup, &out.VirtualPortGroup
		*out = new(XEVirtualPortGroupConfig)
		**out = **in
	}
	if in.AppGigabitEthernet != nil {
		in, out := &in.AppGigabitEthernet, &out.AppGigabitEthernet
		*out = new(XEAppGigabitEthernetConfig)
		**out = **in
	}
	if in.Management != nil {
		in, out := &in.Management, &out.Management
		*out = new(XEManagementConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEInterfaceConfig.
func (in *XEInterfaceConfig) DeepCopy() *XEInterfaceConfig {
	if in == nil {
		return nil
	}
	out := new(XEInterfaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEManagementConfig) DeepCopyInto(out *XEManagementConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEManagementConfig.
func (in *XEManagementConfig) DeepCopy() *XEManagementConfig {
	if in == nil {
		return nil
	}
	out := new(XEManagementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XENetworkConfig) DeepCopyInto(out *XENetworkConfig) {
	*out = *in
	if in.Interface != nil {
		in, out := &in.Interface, &out.Interface
		*out = new(XEInterfaceConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XENetworkConfig.
func (in *XENetworkConfig) DeepCopy() *XENetworkConfig {
	if in == nil {
		return nil
	}
	out := new(XENetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEVirtualPortGroupConfig) DeepCopyInto(out *XEVirtualPortGroupConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEVirtualPortGroupConfig.
func (in *XEVirtualPortGroupConfig) DeepCopy() *XEVirtualPortGroupConfig {
	if in == nil {
		return nil
	}
	out := new(XEVirtualPortGroupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEVlanInterfaceConfig) DeepCopyInto(out *XEVlanInterfaceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEVlanInterfaceConfig.
func (in *XEVlanInterfaceConfig) DeepCopy() *XEVlanInterfaceConfig {
	if in == nil {
		return nil
	}
	out := new(XEVlanInterfaceConfig)
	in.DeepCopyInto(out)
	return out
}
